import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { FiArrowRight, FiDownload, FiStar, FiUsers, FiZap } from 'react-icons/fi'
import { motion } from 'framer-motion'
import { wallpaperAPI, categoryAPI } from '../utils/api'

const Home = () => {
  const [featuredWallpapers, setFeaturedWallpapers] = useState([])
  const [categories, setCategories] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [wallpapersRes, categoriesRes] = await Promise.all([
          wallpaperAPI.getFeatured(),
          categoryAPI.getAll()
        ])
        setFeaturedWallpapers(wallpapersRes.data.data.wallpapers)
        setCategories(categoriesRes.data.data.categories)
      } catch (error) {
        console.error('Error fetching data:', error)
      } finally {
        setLoading(false)
      }
    }

    fetchData()
  }, [])

  return (
    <div className="pt-16">
      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden">
        {/* Background gradient */}
        <div className="absolute inset-0 bg-gradient-to-br from-primary-900/20 via-black to-pink-900/20" />

        {/* Animated background elements */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 -left-48 w-96 h-96 bg-primary-600/20 rounded-full blur-3xl animate-pulse" />
          <div className="absolute bottom-1/4 -right-48 w-96 h-96 bg-pink-600/20 rounded-full blur-3xl animate-pulse" />
        </div>

        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-32 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h1 className="text-5xl md:text-7xl font-bold mb-6">
              <span className="gradient-text">AI-Powered Wallpapers</span>
              <br />
              <span className="text-white">For Every Screen</span>
            </h1>
            <p className="text-xl md:text-2xl text-gray-300 mb-8 max-w-3xl mx-auto">
              Discover thousands of stunning, high-resolution wallpapers generated by advanced AI.
              Transform your devices with breathtaking visuals.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-4">
              <Link
                to="/gallery"
                className="group px-8 py-4 bg-gradient-to-r from-primary-600 to-pink-600 rounded-full text-white font-semibold hover:shadow-lg hover:shadow-primary-500/50 transition flex items-center space-x-2"
              >
                <span>Explore Gallery</span>
                <FiArrowRight className="group-hover:translate-x-1 transition" />
              </Link>
              <Link
                to="/pricing"
                className="px-8 py-4 glass rounded-full text-white font-semibold hover:bg-white/10 transition"
              >
                View Pricing
              </Link>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-3 gap-8 mt-16 max-w-2xl mx-auto">
              <div className="text-center">
                <div className="text-3xl md:text-4xl font-bold gradient-text mb-2">10K+</div>
                <div className="text-gray-400">Wallpapers</div>
              </div>
              <div className="text-center">
                <div className="text-3xl md:text-4xl font-bold gradient-text mb-2">50K+</div>
                <div className="text-gray-400">Downloads</div>
              </div>
              <div className="text-center">
                <div className="text-3xl md:text-4xl font-bold gradient-text mb-2">5K+</div>
                <div className="text-gray-400">Happy Users</div>
              </div>
            </div>
          </motion.div>
        </div>

        {/* Scroll indicator */}
        <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce">
          <div className="w-6 h-10 border-2 border-white/30 rounded-full flex justify-center">
            <div className="w-1 h-3 bg-white/50 rounded-full mt-2" />
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gradient-to-b from-black to-gray-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4 gradient-text">
              Why Choose Us?
            </h2>
            <p className="text-xl text-gray-400">
              The best platform for AI-generated wallpapers
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="glass p-8 rounded-2xl hover:bg-white/10 transition"
            >
              <div className="w-12 h-12 bg-gradient-to-br from-primary-500 to-pink-500 rounded-lg flex items-center justify-center mb-4">
                <FiZap className="text-white" size={24} />
              </div>
              <h3 className="text-2xl font-bold mb-3 text-white">AI-Powered</h3>
              <p className="text-gray-400">
                All wallpapers are generated using state-of-the-art AI models for unique,
                high-quality results.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="glass p-8 rounded-2xl hover:bg-white/10 transition"
            >
              <div className="w-12 h-12 bg-gradient-to-br from-primary-500 to-pink-500 rounded-lg flex items-center justify-center mb-4">
                <FiDownload className="text-white" size={24} />
              </div>
              <h3 className="text-2xl font-bold mb-3 text-white">Unlimited Downloads</h3>
              <p className="text-gray-400">
                Download as many wallpapers as you want with our subscription plans. No limits.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="glass p-8 rounded-2xl hover:bg-white/10 transition"
            >
              <div className="w-12 h-12 bg-gradient-to-br from-primary-500 to-pink-500 rounded-lg flex items-center justify-center mb-4">
                <FiStar className="text-white" size={24} />
              </div>
              <h3 className="text-2xl font-bold mb-3 text-white">High Resolution</h3>
              <p className="text-gray-400">
                All wallpapers available in 4K resolution and multiple formats for any device.
              </p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Categories Section */}
      <section className="py-20 bg-gray-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-4 gradient-text">
              Browse Categories
            </h2>
            <p className="text-xl text-gray-400">
              Find the perfect wallpaper for your style
            </p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
            {categories.slice(0, 6).map((category) => (
              <Link
                key={category._id}
                to={`/gallery/${category.slug}`}
                className="glass p-6 rounded-xl hover:bg-white/10 transition text-center group"
              >
                <div className="text-4xl mb-3">{category.icon}</div>
                <h3 className="text-white font-semibold group-hover:text-primary-400 transition">
                  {category.name}
                </h3>
                <p className="text-gray-400 text-sm mt-1">{category.wallpaperCount} items</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Featured Wallpapers */}
      <section className="py-20 bg-gradient-to-b from-gray-900 to-black">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between mb-12">
            <h2 className="text-4xl md:text-5xl font-bold gradient-text">
              Featured Wallpapers
            </h2>
            <Link
              to="/gallery"
              className="flex items-center space-x-2 text-primary-400 hover:text-primary-300 transition"
            >
              <span>View All</span>
              <FiArrowRight />
            </Link>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {featuredWallpapers.slice(0, 8).map((wallpaper) => (
              <Link
                key={wallpaper._id}
                to={`/wallpaper/${wallpaper.slug}`}
                className="group relative overflow-hidden rounded-xl aspect-[3/4] image-hover"
              >
                <div
                  className="w-full h-full bg-cover bg-center transition-transform duration-300 group-hover:scale-110"
                  style={{
                    backgroundImage: `url(${wallpaper.images?.thumbnail?.url || '/placeholder.jpg'})`
                  }}
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                <div className="absolute bottom-0 left-0 right-0 p-4 translate-y-full group-hover:translate-y-0 transition-transform">
                  <h3 className="text-white font-semibold text-lg mb-1">
                    {wallpaper.title}
                  </h3>
                  <div className="flex items-center space-x-4 text-sm text-gray-300">
                    <span className="flex items-center space-x-1">
                      <FiDownload size={14} />
                      <span>{wallpaper.stats?.downloads || 0}</span>
                    </span>
                    <span className="flex items-center space-x-1">
                      <FiStar size={14} />
                      <span>{wallpaper.stats?.favorites || 0}</span>
                    </span>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-primary-900/30 to-pink-900/30">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-4xl md:text-5xl font-bold mb-6 gradient-text">
            Ready to Transform Your Screens?
          </h2>
          <p className="text-xl text-gray-300 mb-8">
            Join thousands of users and get access to premium AI-generated wallpapers
          </p>
          <Link
            to="/register"
            className="inline-block px-8 py-4 bg-gradient-to-r from-primary-600 to-pink-600 rounded-full text-white font-semibold hover:shadow-lg hover:shadow-primary-500/50 transition"
          >
            Start Free Trial
          </Link>
        </div>
      </section>
    </div>
  )
}

export default Home
