require('dotenv').config();
const mongoose = require('mongoose');
const User = require('../models/User');
const Category = require('../models/Category');
const Wallpaper = require('../models/Wallpaper');

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true
    });
    console.log('MongoDB Connected');
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
};

const seedData = async () => {
  try {
    // Clear existing data
    await User.deleteMany();
    await Category.deleteMany();
    await Wallpaper.deleteMany();

    console.log('Cleared existing data');

    // Create admin user
    const admin = await User.create({
      name: 'Admin User',
      email: 'admin@aiwallpaper.com',
      password: 'admin123',
      role: 'admin',
      subscription: {
        plan: 'enterprise',
        status: 'active',
        currentPeriodStart: new Date(),
        currentPeriodEnd: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000)
      }
    });

    // Create test users
    const user1 = await User.create({
      name: 'John Doe',
      email: 'john@example.com',
      password: 'password123',
      subscription: {
        plan: 'pro',
        status: 'active',
        currentPeriodStart: new Date(),
        currentPeriodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
      }
    });

    const user2 = await User.create({
      name: 'Jane Smith',
      email: 'jane@example.com',
      password: 'password123',
      subscription: {
        plan: 'basic',
        status: 'active',
        currentPeriodStart: new Date(),
        currentPeriodEnd: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
      }
    });

    console.log('Created users');

    // Create categories
    const categories = await Category.insertMany([
      {
        name: 'Abstract',
        slug: 'abstract',
        description: 'Abstract AI-generated art and patterns',
        color: '#6366f1',
        icon: '🎨',
        order: 1,
        seoMetadata: {
          title: 'Abstract AI Wallpapers',
          description: 'Stunning abstract wallpapers generated by AI',
          keywords: ['abstract', 'ai art', 'wallpaper']
        }
      },
      {
        name: 'Nature',
        slug: 'nature',
        description: 'Beautiful landscapes and natural scenes',
        color: '#10b981',
        icon: '🌿',
        order: 2,
        seoMetadata: {
          title: 'Nature AI Wallpapers',
          description: 'AI-generated nature and landscape wallpapers',
          keywords: ['nature', 'landscape', 'wallpaper']
        }
      },
      {
        name: 'Space',
        slug: 'space',
        description: 'Cosmic scenes and celestial wonders',
        color: '#8b5cf6',
        icon: '🌌',
        order: 3
      },
      {
        name: 'Minimal',
        slug: 'minimal',
        description: 'Clean and minimalist designs',
        color: '#64748b',
        icon: '⚪',
        order: 4
      },
      {
        name: 'Cyberpunk',
        slug: 'cyberpunk',
        description: 'Futuristic neon-lit cityscapes',
        color: '#ec4899',
        icon: '🌃',
        order: 5
      },
      {
        name: 'Fantasy',
        slug: 'fantasy',
        description: 'Magical and fantastical worlds',
        color: '#f59e0b',
        icon: '🏰',
        order: 6
      }
    ]);

    console.log('Created categories');

    // Create sample wallpapers
    const wallpapers = [];

    const wallpaperData = [
      {
        title: 'Neon Dreams',
        category: 'cyberpunk',
        description: 'A vibrant cyberpunk cityscape with neon lights reflecting on wet streets',
        tags: ['cyberpunk', 'neon', 'city', 'futuristic']
      },
      {
        title: 'Mountain Sunrise',
        category: 'nature',
        description: 'Majestic mountains bathed in golden sunrise light',
        tags: ['nature', 'mountains', 'sunrise', 'landscape']
      },
      {
        title: 'Abstract Flow',
        category: 'abstract',
        description: 'Smooth flowing gradients in vibrant colors',
        tags: ['abstract', 'gradient', 'colorful', 'modern']
      },
      {
        title: 'Galactic Nebula',
        category: 'space',
        description: 'Stunning nebula with swirling cosmic gases',
        tags: ['space', 'nebula', 'cosmos', 'stars']
      },
      {
        title: 'Minimal Waves',
        category: 'minimal',
        description: 'Simple geometric waves in pastel colors',
        tags: ['minimal', 'geometric', 'pastel', 'clean']
      },
      {
        title: 'Dragon Castle',
        category: 'fantasy',
        description: 'A mystical castle with a dragon flying overhead',
        tags: ['fantasy', 'dragon', 'castle', 'magical']
      },
      {
        title: 'Ocean Deep',
        category: 'nature',
        description: 'Underwater scene with rays of light penetrating the depths',
        tags: ['nature', 'ocean', 'underwater', 'blue']
      },
      {
        title: 'Digital Matrix',
        category: 'abstract',
        description: 'Matrix-style digital rain with glowing code',
        tags: ['abstract', 'digital', 'matrix', 'code']
      },
      {
        title: 'Mars Landscape',
        category: 'space',
        description: 'Red Martian landscape with distant mountains',
        tags: ['space', 'mars', 'planet', 'landscape']
      },
      {
        title: 'Zen Garden',
        category: 'minimal',
        description: 'Peaceful zen garden with simple elements',
        tags: ['minimal', 'zen', 'peaceful', 'meditation']
      },
      {
        title: 'Electric Storm',
        category: 'cyberpunk',
        description: 'Futuristic city during an electrical storm',
        tags: ['cyberpunk', 'storm', 'lightning', 'dramatic']
      },
      {
        title: 'Forest Path',
        category: 'nature',
        description: 'Sunlit path through a dense forest',
        tags: ['nature', 'forest', 'path', 'trees']
      }
    ];

    for (const data of wallpaperData) {
      const category = categories.find(c => c.slug === data.category);

      wallpapers.push({
        title: data.title,
        slug: data.title.toLowerCase().replace(/\s+/g, '-'),
        description: data.description,
        categories: [category._id],
        tags: data.tags,
        images: {
          thumbnail: {
            url: `/images/wallpapers/${data.title.toLowerCase().replace(/\s+/g, '-')}-thumb.jpg`,
            width: 400,
            height: 300,
            size: 50000
          },
          preview: {
            url: `/images/wallpapers/${data.title.toLowerCase().replace(/\s+/g, '-')}-preview.jpg`,
            width: 1920,
            height: 1080,
            size: 500000,
            watermarked: true
          },
          original: {
            url: `/images/wallpapers/${data.title.toLowerCase().replace(/\s+/g, '-')}-original.jpg`,
            width: 3840,
            height: 2160,
            size: 2000000,
            format: 'jpg'
          }
        },
        aiModel: {
          name: 'DALL-E 3',
          version: '1.0',
          parameters: {
            style: 'vivid',
            quality: 'hd'
          }
        },
        artist: {
          name: 'AI Generated',
          attribution: 'Created using advanced AI'
        },
        copyright: {
          owner: 'AI Wallpaper Platform',
          license: 'both',
          attributionRequired: false
        },
        pricing: {
          requiresSubscription: true,
          minimumPlan: 'basic'
        },
        stats: {
          views: Math.floor(Math.random() * 1000) + 100,
          downloads: Math.floor(Math.random() * 500) + 50,
          favorites: Math.floor(Math.random() * 200) + 20
        },
        status: 'approved',
        featured: Math.random() > 0.5,
        uploadedBy: admin._id,
        approvedBy: admin._id,
        approvedAt: new Date(),
        seoMetadata: {
          title: `${data.title} - AI Wallpaper`,
          description: data.description,
          keywords: data.tags
        }
      });
    }

    const createdWallpapers = await Wallpaper.insertMany(wallpapers);

    // Update category wallpaper counts
    for (const category of categories) {
      const count = createdWallpapers.filter(w =>
        w.categories.some(c => c.toString() === category._id.toString())
      ).length;

      category.wallpaperCount = count;
      await category.save();
    }

    console.log('Created wallpapers');

    console.log('\n✅ Database seeded successfully!');
    console.log('\nTest Accounts:');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('Admin:');
    console.log('  Email: admin@aiwallpaper.com');
    console.log('  Password: admin123');
    console.log('\nPro User:');
    console.log('  Email: john@example.com');
    console.log('  Password: password123');
    console.log('\nBasic User:');
    console.log('  Email: jane@example.com');
    console.log('  Password: password123');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

// Run seed
connectDB().then(seedData);
